it's been created a new github workflows: dev_local.yml

diff --git a/.github/workflows/dev_loca.yml b/.github/workflows/dev_loca.yml
--- a/.github/workflows/dev_loca.yml
+++ b/.github/workflows/dev_loca.yml
@@ -8,8 +8,122 @@ on:
       - 'wip-*'
 
 jobs:
-  oneui:
-    name: Build One UI
+  #oneui:
+  #  name: Build One UI
+  #  runs-on: self-hosted
+#
+  #  strategy:
+  #    fail-fast: true
+  #    
+  #  steps:
+  #  - uses: actions/checkout@v2
+#
+  #  - uses: szenius/set-timezone@v1.0
+  #    with:
+  #      timezoneLinux: "Europe/Rome"
+  #      timezoneMacos: "Europe/Rome"
+  #      timezoneWindows: "Italy Standard Time"
+#
+  #  - name: Export build branch
+  #    run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+  #    id: branch_name
+#
+  #  #- name: Install Debian/Ubuntu dependencies
+  #  #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y
+#
+  #  - name: Build Mint kernel
+  #    run: |
+  #        set -eo pipefail
+  #        echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
+  #        export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
+  #        ./build.sh --magisk --automated --device a50 --variant oneui
+#
+  #  - name: Prepare release package
+  #    run: |
+  #        mkdir -p ./release
+  #        mv -f `find ./ -iname MintBeta-*.zip` ./release/
+#
+  #  - name: Upload release package
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: oneui_beta-${{ github.run_number }}
+  #      path: 'release'
+  #      if-no-files-found: error
+#
+  #  - name: Prepare build config artifact
+  #    run: |
+  #        cp .config ./release/kernel_config_a50.txt
+#
+  #  - name: Upload kernel image artifact
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: One UI Kernel Image
+  #      path: 'tools/make/boot.img'
+  #      if-no-files-found: error
+
+  #  - name: Upload build config artifact
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: One UI Kernel Config
+  #      path: 'release/kernel_config_a50.txt'
+  #      if-no-files-found: error
+
+  #snowcone:
+  #  name: Build Lineage/AOSP 12
+  #  runs-on: self-hosted
+#
+  #  strategy:
+  #    fail-fast: true
+  #    
+  #  steps:
+  #  - uses: actions/checkout@v2
+#
+  #  - uses: szenius/set-timezone@v1.0
+  #    with:
+  #      timezoneLinux: "Europe/Rome"
+  #      timezoneMacos: "Europe/Rome"
+  #      timezoneWindows: "Italy Standard Time"
+#
+  #  - name: Export build branch
+  #    run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+  #    id: branch_name
+#
+  # # - name: Install Debian/Ubuntu dependencies
+  # #   run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y
+#
+  #  - name: Build Mint kernel
+  #    run: |
+  #        set -eo pipefail
+  #        echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
+  #        export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
+  #        ./build.sh --magisk --automated --device a50 --variant aosp --android 12
+#
+  #  - name: Prepare release package
+  #    run: |
+  #        mkdir -p ./release
+  #        mv -f `find ./ -iname MintBeta-*.zip` ./release/
+#
+  #  - name: Upload release package
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: snowcone_beta-${{ github.run_number }}
+  #      path: 'release'
+  #      if-no-files-found: error
+#
+  #  - name: Prepare build config artifact
+  #    run: |
+  #        cp .config ./release/kernel_config_a50.txt
+#
+  #  - name: Upload build config artifact
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: AOSP 12 Kernel Config
+  #      path: 'release/kernel_config_a50.txt'
+  #      if-no-files-found: error
+
+  aosp-s-e:
+    name: Build AOSP 12 (Enforcing)
+    #if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
     runs-on: self-hosted
 
     strategy:
@@ -28,101 +142,51 @@ jobs:
       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
       id: branch_name
 
+    #- name: Update Debian/Ubuntu Repositories
+    #  run: sudo apt-get update
+#
     #- name: Install Debian/Ubuntu dependencies
-    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y
-
+    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y
+#
     - name: Build Mint kernel
       run: |
           set -eo pipefail
           echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
-          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
-          ./build.sh --magisk --automated --device a50 --variant oneui
+          ./build.sh --magisk --automated --device a50 --variant aosp --android 12
 
     - name: Prepare release package
       run: |
           mkdir -p ./release
-          mv -f `find ./ -iname MintBeta-*.zip` ./release/
-
-    - name: Upload release package
-      uses: actions/upload-artifact@v2
-      with:
-        name: oneui_beta-${{ github.run_number }}
-        path: 'release'
-        if-no-files-found: error
+          mv -f `find ./ -iname Mint*-*.zip` ./release/
 
     - name: Prepare build config artifact
       run: |
-          cp .config ./release/kernel_config_a50.txt
+          cp .config ./release/kernel_config_a50_aosp-s-e.txt
 
     - name: Upload kernel image artifact
       uses: actions/upload-artifact@v2
       with:
-        name: One UI Kernel Image
+        name: AOSP 12 Kernel Image (Enforcing)
         path: 'tools/make/boot.img'
         if-no-files-found: error
 
     - name: Upload build config artifact
       uses: actions/upload-artifact@v2
       with:
-        name: One UI Kernel Config
-        path: 'release/kernel_config_a50.txt'
+        name: Kernel Configs
+        path: 'release/kernel_config_a50_aosp-s-e.txt'
         if-no-files-found: error
-
-  snowcone:
-    name: Build Lineage/AOSP 12
-    runs-on: self-hosted
-
-    strategy:
-      fail-fast: true
-      
-    steps:
-    - uses: actions/checkout@v2
-
-    - uses: szenius/set-timezone@v1.0
-      with:
-        timezoneLinux: "Europe/Rome"
-        timezoneMacos: "Europe/Rome"
-        timezoneWindows: "Italy Standard Time"
-
-    - name: Export build branch
-      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-      id: branch_name
-
-   # - name: Install Debian/Ubuntu dependencies
-   #   run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y
-
-    - name: Build Mint kernel
-      run: |
-          set -eo pipefail
-          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
-          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
-          ./build.sh --magisk --automated --device a50 --variant aosp --android 12
-
-    - name: Prepare release package
-      run: |
-          mkdir -p ./release
-          mv -f `find ./ -iname MintBeta-*.zip` ./release/
 
     - name: Upload release package
       uses: actions/upload-artifact@v2
       with:
-        name: snowcone_beta-${{ github.run_number }}
+        name: Release
         path: 'release'
         if-no-files-found: error
 
-    - name: Prepare build config artifact
-      run: |
-          cp .config ./release/kernel_config_a50.txt
-
-    - name: Upload build config artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: AOSP 12 Kernel Config
-        path: 'release/kernel_config_a50.txt'
-        if-no-files-found: error
-
-  snowcone_permissive:
-    name: Build Lineage/AOSP 12 - Permissive
+  aosp-s-p:
+    name: Build AOSP 12 (Permissive)
+    #if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
     runs-on: self-hosted
 
     strategy:
@@ -141,43 +205,225 @@ jobs:
       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
       id: branch_name
 
+    #- name: Update Debian/Ubuntu Repositories
+    #  run: sudo apt-get update
+#
     #- name: Install Debian/Ubuntu dependencies
-    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y
+    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y
+#
+    - name: Build Mint kernel
+      run: |
+          set -eo pipefail
+          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
+          ./build.sh --magisk --automated --device a50 --variant aosp --android 12 --permissive
+
+    - name: Prepare release package
+      run: |
+          mkdir -p ./release
+          mv -f `find ./ -iname Mint*-*.zip` ./release/
+
+    - name: Prepare build config artifact
+      run: |
+          cp .config ./release/kernel_config_a50_aosp-s-p.txt
+
+    - name: Upload kernel image artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: AOSP 12 Kernel Image (Permissive)
+        path: 'tools/make/boot.img'
+        if-no-files-found: error
+
+    - name: Upload build config artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: Kernel Configs
+        path: 'release/kernel_config_a50_aosp-s-p.txt'
+        if-no-files-found: error
+
+    - name: Upload release package
+      uses: actions/upload-artifact@v2
+      with:
+        name: Release
+        path: 'release'
+        if-no-files-found: error
+
+  aosp-s-k-e:
+    name: Build AOSP 12 (Enforcing ; KernelSU)
+    #if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
+    runs-on: self-hosted
+
+    strategy:
+      fail-fast: true
+      
+    steps:
+    - uses: actions/checkout@v2
+
+    - uses: szenius/set-timezone@v1.0
+      with:
+        timezoneLinux: "Europe/Rome"
+        timezoneMacos: "Europe/Rome"
+        timezoneWindows: "Italy Standard Time"
+
+    - name: Export build branch
+      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+      id: branch_name
 
     - name: Build Mint kernel
       run: |
           set -eo pipefail
           echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
-          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
-          ./build.sh --automated --device a50 --variant aosp --android 12 --permissive --magisk
+          ./build.sh --kernelsu --automated --device a50 --variant aosp --android 12
 
     - name: Prepare release package
       run: |
           mkdir -p ./release
-          mv -f `find ./ -iname MintBeta-*.zip` ./release/
-
-    - name: Upload release package
-      uses: actions/upload-artifact@v2
-      with:
-        name: snowcone-permissive_beta-${{ github.run_number }}
-        path: 'release'
-        if-no-files-found: error
+          mv -f `find ./ -iname Mint*-*.zip` ./release/
 
     - name: Prepare build config artifact
       run: |
-          cp .config ./release/kernel_config_a50.txt
+          cp .config ./release/kernel_config_a50_aosp-s-k-e.txt
+
+    - name: Upload kernel image artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: AOSP 12 Kernel Image (Enforcing)
+        path: 'tools/make/boot.img'
+        if-no-files-found: error
 
     - name: Upload build config artifact
       uses: actions/upload-artifact@v2
       with:
-        name: AOSP 12 Permissive Kernel Config
-        path: 'release/kernel_config_a50.txt'
+        name: Kernel Configs
+        path: 'release/kernel_config_a50_aosp-s-k-e.txt'
         if-no-files-found: error
+
+    - name: Upload release package
+      uses: actions/upload-artifact@v2
+      with:
+        name: Release
+        path: 'release'
+        if-no-files-found: error
+
+  aosp-s-k-p:
+    name: Build AOSP 12 (Permissive ; KernelSU)
+    #if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
+    runs-on: self-hosted
+
+    strategy:
+      fail-fast: true
+      
+    steps:
+    - uses: actions/checkout@v2
+
+    - uses: szenius/set-timezone@v1.0
+      with:
+        timezoneLinux: "Europe/Rome"
+        timezoneMacos: "Europe/Rome"
+        timezoneWindows: "Italy Standard Time"
+
+    - name: Export build branch
+      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+      id: branch_name
+
+    #- name: Update Debian/Ubuntu Repositories
+    #  run: sudo apt-get update
+#
+    #- name: Install Debian/Ubuntu dependencies
+    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y
+#
+    - name: Build Mint kernel
+      run: |
+          set -eo pipefail
+          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
+          ./build.sh --kernelsu --automated --device a50 --variant aosp --android 12 --permissive
+
+    - name: Prepare release package
+      run: |
+          mkdir -p ./release
+          mv -f `find ./ -iname Mint*-*.zip` ./release/
+
+    - name: Prepare build config artifact
+      run: |
+          cp .config ./release/kernel_config_a50_aosp-s-k-p.txt
+
+    - name: Upload kernel image artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: AOSP 12 Kernel Image (Permissive)
+        path: 'tools/make/boot.img'
+        if-no-files-found: error
+
+    - name: Upload build config artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: Kernel Configs
+        path: 'release/kernel_config_a50_aosp-s-k-p.txt'
+        if-no-files-found: error
+
+    - name: Upload release package
+      uses: actions/upload-artifact@v2
+      with:
+        name: Release
+        path: 'release'
+        if-no-files-found: error
+
+  #snowcone_permissive:
+  #  name: Build Lineage/AOSP 12 - Permissive
+  #  runs-on: self-hosted
+#
+  #  strategy:
+  #    fail-fast: true
+  #    
+  #  steps:
+  #  - uses: actions/checkout@v2
+#
+  #  - uses: szenius/set-timezone@v1.0
+  #    with:
+  #      timezoneLinux: "Europe/Rome"
+  #      timezoneMacos: "Europe/Rome"
+  #      timezoneWindows: "Italy Standard Time"
+#
+  #  - name: Export build branch
+  #    run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+  #    id: branch_name
+#
+  #  #- name: Install Debian/Ubuntu dependencies
+  #  #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y
+#
+  #  - name: Build Mint kernel
+  #    run: |
+  #        set -eo pipefail
+  #        echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
+  #        export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
+  #        ./build.sh --automated --device a50 --variant aosp --android 12 --permissive --magisk
+#
+  #  - name: Prepare release package
+  #    run: |
+  #        mkdir -p ./release
+  #        mv -f `find ./ -iname MintBeta-*.zip` ./release/
+#
+  #  - name: Upload release package
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: snowcone-permissive_beta-${{ github.run_number }}
+  #      path: 'release'
+  #      if-no-files-found: error
+#
+  #  - name: Prepare build config artifact
+  #    run: |
+  #        cp .config ./release/kernel_config_a50.txt
+#
+  #  - name: Upload build config artifact
+  #    uses: actions/upload-artifact@v2
+  #    with:
+  #      name: AOSP 12 Permissive Kernel Config
+  #      path: 'release/kernel_config_a50.txt'
+  #      if-no-files-found: error
 
   release:
     name: Release files and configs
     if: always()
-    needs: [oneui, snowcone, snowcone_permissive]
+    needs: [aosp-s-e, aosp-s-p, aosp-s-k-e, aosp-s-k-p]
     runs-on: self-hosted
     strategy:
       fail-fast: true
